### PR TITLE
Hotfix laravel

### PR DESCRIPTION
**Pull request by vQFire**
**What is it supposed to do**
It is should be the api

 **How can we test your branch**
There is an API on the way to explain

 **What browsers have been checked**
- [x] Chrome
- [x] Firefox
- [x] Opera
- [x] Internet Explorer
- [x] Edge
- [x] Safari

### CODE REVIEW

**Comment by MiguelFieira** [comment]
*Notes*
Make sure to rename `.env.example` to `.env`
    - Make sure the DB:USER = root
    - Make sure the DB:Password = empty
    - Make sure Xampp is running
    - Make a DB with the same db name as in the .env file

Run command `php artisan migrate:refresh --seed` //To update the DB <br>
run command `php artisan serve` // To start the php server <br>
Navigate to `localhost:8000/api/post`

**Review by MiguelFieira — APPROVED** [review]
Needs a interface in the future but it works

**Comment by vQFire** [comment]
I agree that we need an admin panel in the future, but the API will not get an interface....

**Review by Samvdg — APPROVED** [review]
didnt check everything in detail but seems good to me

**Pull request merged**
