### PR TITLE
303 Shouldn't create post when not logged in

### LINKED ISSUE #303: [303] New Post Route Guard
**Current state**
Guests that are not logged in are able to access the 'new-post' page.

image

Also, when user refreshes new-post page they don't see any of their data. Very likely due to mobx not updating the profile store? The author data does update however when you click on an input field. Likely an issue with rendering.

**Expected state**
Guests are not able to access the `localhost:8080/new-post` page and will be redirected to the login page.

Even when user refreshes the new-post page it contains their profile data.

**TO DO**
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3
- [ ] Task ...

**Necessities**
None

**Branch**
303-new-post-route-guard

### PR DESCRIPTION
**Pull request by sribadal**
closes #303

<br />

 **What is it supposed to do**  
This PR is supposed to fix the issue where a not logged in person can visit the /new-post route.

<br />

 **How can we test your branch**  
1. Don't login
2. Visit new-post route

1. Login with your credentials
2. Visit new-post route

You should be able to visit the new-post route only if you are logged in.

<br />

 **Additional notes**  
Things to keep in mind regarding the PR that don't fit in the previous two headings. 

<br />

**1. General checklist**
- [x] a. Tested happy flow.
- [x] b. Tested unhappy flow.
- [x] c. No unexpected exceptions.
- [x] d. No code with high complexity. (Big O)
- [x] e. EOF newline.
- [x] f. No linter warnings or errors.

<br />

**2. If relevant, front-end checklist**
- [ ] a. Responsive. (Desktop all the way to mobile 320px)
- [ ] b. Using SCSS variables where relevant.
- [ ] c. Relevant class names
- [ ] d. No modified global SCSS properties, except if necessary and fully tested the impact.
- [ ] e. Checked [caniuse](https://caniuse.com) for more modern CSS properties.

<br />

**3. If relevant, back-end checklist**
- [ ] a. No unhandled promise rejections.
- [ ] b. Seeders still functional.
- [ ] c. No primary-key violations.
- [ ] d. Normalization, at least [3NF](https://en.wikipedia.org/wiki/Database_normalization).
- [ ] e. Used guards (middleware) where necessary and tested if route is guarded.

<br />

**4. If relevant, test these browsers**
- [x] a. Chrome
- [x] b. Firefox
- [x] c. Opera
- [x] d. Edge
- [ ] e. Safari

---

**PR Rules**  
*1. Add relevant labels.*  
*2. Select at least two reviewers.*  
*3. Assign all reviewers allowed to merge the branch, including yourself.*  
*4. If relevant to the sprint, put related issue in 'Awaiting Approval' column on project board.*  
*5. Add to the corresponding [milestone](https://github.com/AjobK/Seaqull/milestones).*

<br />

**Reviewer info**  
*1. You can use aliases to refer to specific PR checklist items. For example 'Hey @JohnDoe, for this line please check 3.a and 1.d.'*  
*2. Where possible, please use the suggestions feature in github so the author has a better idea of the solution you had in mind.*   

<br />

> This form should be filled in by the author of this PR.

### CODE REVIEW

**Review by ryankroon00 — DISMISSED** [review]

**Comment by AjobK** [comment]
https://blog.netcetera.com/how-to-create-guarded-routes-for-your-react-app-d2fe7c7b6122

image

**Review by AjobK — CHANGES_REQUESTED** [review]
Make reusable check comment above

**Review by AjobK — CHANGES_REQUESTED** [review]
image

**Review by AjobK — CHANGES_REQUESTED** [review]
Redirect to login

**Comment by sribadal** [comment]
> Redirect to login

Fixed in commit: 143140a21fc671f4b2fec6e43d4bac5ea8bfd077

**Review by AjobK — APPROVED** [review]
Super cool

**Pull request merged**
