### PR TITLE
282 delete posts

### LINKED ISSUE #284: [284] Delete posts
**Current state**
Authors are unable to delete their posts.

**Expected state**
Authors can delete posts with the trashcan icon at the bottom of their post. They should get a popup asking if they really want to delete the post.

**TO DO**
- [x] Trashcan (DELETE) icon
- [x] Functional icon SOFT DELETES in DB
- [x] Popup asking if the author is sure they want to delete the post

**Necessities**
None

**Branch**
282-delete-posts (was supposed to be 284 but yeah)

### PR DESCRIPTION
**Pull request by jerohero**
closes #284 

<br />

 **What is it supposed to do**  
Post owners and admins are able to delete posts from the front-end. These posts are soft deleted, meaning they're actually archived (implemented in another branch) and will still exist while not appearing anymore.

<br />

 **How can we test your branch**  
Create a post. While creating the post, the delete button should not be visible. After this, a delete button should appear at the bottom right.
image
The delete button should not appear on posts that aren't created by the user you're logged in on. It should also appear when you're an admin, but this can't be tested due to an external issue (see additional notes).

<br />

 **Additional notes**  
Backend:
In _postRoutes_ I replaced the _hasPermissions_ middleware at the _archivePost_ route with a new _hasPostPermissions_ middleware. This does the same as _hasPermissions_, but also checks if the user owns the post that is to be archived. As I'm not experienced with Express.js it might be worth looking at.

The pre-generated admin user appears to have a user role and not an admin role (this.props.store.profile.role returns 'user'). I wasn't able to test the delete functionality for admins due to this.

There is currently an issue in develop that crashes the application on startup, which should be fixed in the 1.1 hotfix branch.

<br />

**1. General checklist**
- [x] a. Tested happy flow.
- [x] b. Tested unhappy flow.
- [x] c. No unexpected exceptions.
- [x] d. No code with high complexity. (Big O)
- [x] e. EOF newline.
- [x] f. No floating comma's and spaces.
- [x] g. No unexpected/unhandled errors.
- [x] h. Lines no longer than 'guideline' in IDE.
- [x] i. Correct indentation.
- [x] j. No usage of legacy functionalities.
- [x] k. (JS) Curly braces on the sameline as reserved keywords *(`if () {` instead of `{` on line below)*
- [x] l. (JS) No double quotes.
- [x] m. (JS) Single newline above unique code structures and reserved keywords.
- [x] n. (JS) Variables bundled where possible.
- [x] o. (JS) No semi-colons except where they have a functional necessity, such as for-loops.
- [x] p. (JS) No code that is meant exclusively for development, such as console.logs for data preview.

<br />

**2. If relevant, front-end checklist**
- [x] a. Responsive. (Desktop all the way to mobile 320px)
- [x] b. Using SCSS variables where relevant.
- [x] c. Relevant class names
- [x] d. No modified global SCSS properties, except if necessary and fully tested the impact.
- [x] e. Checked [caniuse](https://caniuse.com) for more modern CSS properties.

<br />

**3. If relevant, back-end checklist**
- [x] a. No unhandled promise rejections.
- [x] b. Seeders still functional.
- [x] c. No primary-key violations.
- [x] d. Normalization, atleast [3NF](https://en.wikipedia.org/wiki/Database_normalization).
- [x] e. Used guards (middleware) where necessary and tested if route is guarded.

<br />

**4. If relevant, test these browsers**
- [x] a. Chrome
- [x] b. Firefox
- [ ] c. Opera
- [x] d. Edge
- [ ] e. Safari

### CODE REVIEW

**Comment by AjobK** [comment]
'DELETE POST' overlay on banner should be commented in code. Add a TODO to it stating that we will uncomment it again when creating the 'EDIT POST BANNER' functionality. Naturally the code will be modified at that time from delete functionalities to edit banner.

Change delete button to dark grey bin icon with 'DELETE' text next to it (or tooltip).

**Comment by AjobK** [comment]
image

When I've created a post and have been redirected to the view page and I click on the delete button it gives me an error. The error can be seen in the picture above. I can however delete a post when I refresh the page or go to it again through my profile.

More context in image below:

image

**Comment by AjobK** [comment]
image

I can delete posts of other people without even being logged in or being the correct author. Did this with insomnia.

**Comment by AjobK** [comment]
Please change route to something like `/posts/archive` or `/posts/delete` instead of just `/archive`. This is very restricting for possible future archive routes and it doesn't give any context to the fact that you want to archive a post.

**Review by AjobK — CHANGES_REQUESTED** [review]
Please check comments

**Comment by jerohero** [comment]
> image
> 
> I can delete posts of other people without even being logged in or being the correct author. Did this with insomnia.

I can't seem to replicate this issue. Are you sure you weren't logged in already and deleted the post as an admin?

Not logged in:
chrome_brtkxzFWLq

Not logged in as post owner or admin:
chrome_nuXCIcoG07

**Comment by AjobK** [comment]
image

Please change this to something more clear. I get this message when successfully archiving a post.

**Comment by AjobK** [comment]
image

When you attempt to archive a post url that doesn't exist it infinitely loads.

**Review by AjobK — CHANGES_REQUESTED** [review]
Check comments above

**Comment by AjobK** [comment]
image

Getting an error when trying to archive something with insomnia (postman) if I'm not logged in. Likely because of the following line:

image

You don't check whether post.profile exists, which results in infinite loading and an error in the terminal.

**Review by AjobK — APPROVED** [review]
Great work man! @jerohero

**Pull request merged**
